version: '3.8'

services:
  evolution-api:
    container_name: evolution-api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://20.168.13.56:8080
      - AUTHENTICATION_API_KEY=segredodosabor2025
      - CONFIG_SESSION_PHONE_CLIENT=DoceGest Bot
      - CONFIG_SESSION_PHONE_NAME=Segredo do Sabor
      - DATABASE_ENABLED=false
      - QRCODE_LIMIT=30
      - QRCODE_COLOR=#198754
      - LOG_LEVEL=ERROR
      - LOG_COLOR=true
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=http://20.168.13.56/api/webhooks/whatsapp
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      - WEBHOOK_EVENTS_APPLICATION_STARTUP=false
      - WEBHOOK_EVENTS_QRCODE_UPDATED=true
      - WEBHOOK_EVENTS_MESSAGES_SET=true
      - WEBHOOK_EVENTS_MESSAGES_UPSERT=true
      - WEBHOOK_EVENTS_MESSAGES_UPDATE=true
      - WEBHOOK_EVENTS_SEND_MESSAGE=true
      - WEBHOOK_EVENTS_CONNECTION_UPDATE=true
      - STORE_MESSAGES=true
      - STORE_CONTACTS=true
      - STORE_CHATS=true
    volumes:
      - evolution_data:/evolution/store
      - evolution_instances:/evolution/instances
    networks:
      - evolution-network

networks:
  evolution-network:
    driver: bridge

volumes:
  evolution_data:
  evolution_instances:
